name: Build and Push Docker Image
on:
  push:
    branches:
      - master
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create entrypoint.sh
        run: |
          cat << EOF > entrypoint.sh
          #!/bin/sh
          _term() {
            echo "Caught SIGTERM signal!"
            kill -TERM "\$child"
          }
          wait-for mongo:27017 -- python3 /lightedge-wais-mananger.py
          EOF
          chmod +x entrypoint.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: .github/utils/Dockerfile
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_HUB_USER }}/lightedge-wais-manager:latest